
ALTER TABLE public.produtos
ADD COLUMN IF NOT EXISTS referencia text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS categoria_idade text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS genero text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS estilo text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS cor_armacao text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS material_aro text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS material_haste text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS altura_lente integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS tipo_lente text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS subcategoria_acessorio text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS is_acessorio boolean NOT NULL DEFAULT false;
